name: 'Normalized Unicode'
author: 'buddhist-uni'
description: 'Checks for unnormalized Unicode and optionally commits a fix if needed.'
branding:
  icon: 'underline'
  color: 'blue'
inputs:
  transliteration:  # id of input
    description: 'The Unicode style you would like to consider standard'
    required: true
    default: 'Any-NFC'
  check_all:
    description: 'Should it check all files in the repro instead of just the files touched by the last commit?'
    required: true
    default: false
  exit_code:
    description: 'What exit status code should it use if a file was found in need of normalization?'
    required: true
    default: 0
  commit_fix:
    description: 'If a problem is found, should the action automatically commit a fix?'
    required: true
    default: true
  token:
    description: 'A personal access token for pushing the fix to the repo. Required if you want that push to trigger workflows'
    required: false
runs:
  using: 'composite'
  steps:
    - run: |
        mkdir -p "$HOME/.local/bin"
        cd "$HOME/.local/bin"
        wget https://raw.githubusercontent.com/madx/moreutils/master/isutf8.c
        gcc isutf8.c -o isutf8
        rm isutf8.c
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "Built isutf8 and added it to the GITHUB_PATH!"
      shell: bash
    - run: $GITHUB_ACTION_PATH/entrypoint.sh ${{ inputs.transliteration }} ${{ inputs.exit_code }} ${{ inputs.commit_fix }} ${{ inputs.check_all }}
      shell: bash

